name: Pull Request Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
  UnitTesting:
    runs-on: macos-12
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Build and test ( iOS 15.5)
      run: xcodebuild test -scheme FruityVice -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 8'
