name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Build and test ( iOS 15.5)
      run: xcodebuild test -scheme FruityVice -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 8'
